### ISSUE TITLE
Shard images don't render

### ISSUE THREAD

**Issue by Xender0w0** [PlutoyDev/sky-shards#26]
So umm I was selected as a beta member
So I think this where I live a report (?)
The shard images don't render correctly for me

**Comment by PlutoyDev** [comment]
Hi Xender, 
Thank you for reporting it.

Yes, You can report any issue you found / submit any feedback you have here. 
By shard images, do you mean the background images? 
and can you be more specific for "don't render correctly for me"? (overly stretched/not showing) 
A screenshot of what you see will be great. (Add an attachment by clicking "Attach files by ......" bellow the edit box)  
![image](https://user-images.githubusercontent.com/99151858/212437152-69decf24-d1f0-4af4-b35e-4795157647cc.png)

**Comment by PlutoyDev** [comment]
No response after 5 days. Feel free to reopen the issue if you still face this bug.

Suspected is duplicate of #20. Which is related to caching and optimization. The background image will not download if it has never been loaded, so if application is offline when switching themes for the 1st time, the image will be unable to display
