### ISSUE TITLE
Header datetime "Sky time indicator"

### ISSUE THREAD

**Issue by CapoFantasma97** [PlutoyDev/sky-shards#59]
Despite correctly setting timezone and time format, the clock is wrong by 9 hours on the header.
On a positive note, this does not seem to affect the time tables or the countdowns.

![immagine](https://github.com/PlutoyDev/sky-shards/assets/9368910/085bb730-f61a-4e9f-81a5-53c10069e615)
It is still wrong even if set to 12 hours format (in the below example it would display as AM instead of PM).

![immagine](https://github.com/PlutoyDev/sky-shards/assets/9368910/b1b56ca2-4206-4c7a-89d5-8ce3ffc8c20d)

**Comment by PlutoyDev** [comment]
Hi @CapoFantasma97, 
The date time in the header is showing the current date time in Sky (America/Los Angeles) not local time as local time can be found on user's device already, I felt that it is redundant to put local time so opted to put sky time instead.

**Comment by CapoFantasma97** [comment]
> Hi @CapoFantasma97, The date time in the header is showing the current date time in Sky (America/Los Angeles) not local time as local time can be found on user's device already, I felt that it is redundant to put local time so opted to put sky time instead.

@PlutoyDev perhaps it would be beneficial to clarify that, with a short text labeling it as such (similarly to how it is specified in other areas of the page as `Sky Time: (America/Los_Angeles)`).

**Comment by PlutoyDev** [comment]
That is a good idea but given that this application's primary user is on mobile device, the header space is a little tight.
I do have plans to animate the text in substituting the date with "Now in sky:" temporary every few seconds like what has been done in the footer.

Most likely release as part of v5. It won't come out as fast.

**Comment by PlutoyDev** [comment]
Patched using animation in V5

https://github.com/PlutoyDev/sky-shards/assets/99151858/c8fbdedf-33ac-4faf-bcbb-b365e52f1ebd
