### ISSUE TITLE
Negative time difference for relative time in timeline

### ISSUE THREAD

**Issue by lolifamily** [PlutoyDev/sky-shards#60]
For example, if now is 23:00 and there's an event in 01:00 tomorrow, relative time should show 2:00 not -22:00

**Comment by PlutoyDev** [comment]
Hello, could you please share a screenshot of the problem? 
I'm having trouble identifying the specific issue you're mentioning.

Thank you.

**Comment by PlutoyDev** [comment]
Upon further inspection, it appears that I inadvertently introduced a minor bug into the timeline.
It should have subtract present from future, but it was doing it the other way around causing the time to be negative.

Thank you for report the issue, I will get to fixing it.

**Comment by PlutoyDev** [comment]
If I have misunderstood your issue please re-open this issue or open a new one.

**Comment by lolifamily** [comment]
@PlutoyDev You understood right! However in my eyes showing the future event's relative time as negative and past as positive might be counterintuitive, maybe inverse and explain should be better
