### ISSUE TITLE
#60 positive or negative discussion

### ISSUE THREAD

**Issue by lolifamily** [PlutoyDev/sky-shards#62]

**Comment by lolifamily** [comment]
In my eyes showing the future event's relative time as negative and past as positive might be counterintuitive, maybe inverse and explain should be better.

**Comment by PlutoyDev** [comment]
Hi, future event are not negative. It was a bug that has been patched as of #61 please refresh the page.

![IMG_20231011_064616](https://github.com/PlutoyDev/sky-shards/assets/99151858/0d666cff-4649-446c-99fd-5fda52f60456)

The app is a PWA, which will get the load the app (memory first) then tries to check the server for new info, so you might need to refresh again for the new app to show up.
