### ISSUE TITLE
Translations from browser preferences

### ISSUE THREAD

**Issue by ghost** [PlutoyDev/sky-shards#63]
I've noticed recently that the app started adding translations based on my geo-location but I don't use the game itself in this language nor my browser is set in this language for a lot of reasons. I believe there may be more people like me and having to switch languages to properly get some labels is not hard but it's a bit annoying having to do that every time.

Can we get the language selection from the browser preferences instead of the user's IP?

**Comment by PlutoyDev** [comment]
Hi Ricofrede,

Firstly, the language is changeable via the setting buttons in the top right corner of the screen. Feel free to change it to the language of choice. If the language is missing, you can help by translating the app using the link in the footer of the English version. After changing it, the app should be remembered the next time you visit using Localstorage API, unless the app can't store data in your browser, albeit incognito mode, privacy browser, etc.

Language is also configurable through url
For example, https://sky-shards.pages.dev/?lang=en

Secondly, the language of the app is using what the browser provides the app with through the navigator.languages API [source](https://github.com/PlutoyDev/sky-shards/blob/f1fa6e99caf0f21446d578a97c3d2ee6c3235fe7/src/context/Settings.tsx#L65). No IP address required, resolving in server hardware that I will need pay... Too much work 😕. I don't need to record what I don't need, including geo location, IP address, its a waste of money which I have better places to spend, and not on an application that doesn't make money.

For now, I will be closing this issue.
If the app is not working as what I've describe here feel free to reopen the issue or open a new one.

**Comment by ghost** [comment]
@PlutoyDev Yeah I see now that the problem I mentioned only happen to me in Firefox mobile, although it's still a little weird because there is absolutely nothing in my mobile device configured to use Portuguese specially not the browser but it's still forcing the Portuguese translations every time I open the app.

Still this will only be a me problem because I always use browser in private mode so none of the settings will be saved but I'm still pretty sure it's not picking up from my browser preferences in this scenario.

But I absolutely agree with you, not asking you to translate server-side I just thought it wasn't using the browser navigator since mine is set to English and I was still having the page translated.

**Comment by PlutoyDev** [comment]
There was another bug report filled through the feedback form about the language defaulting to Portuguese. I will check through it using Firefox 

As an recommendations for your case you may bookmark this url instead https://sky-shards.pages.dev/?lang=en. This will force the language to en on load and prevent it from checking the browser language.

In the future version, I think I will have the app change the url when the settings is changed so that bookmarking will "save" the data for incognito browser.
