### ISSUE TITLE
The timeline is wrong on legacy time line 

### ISSUE THREAD

**Issue by Uncurse** [PlutoyDev/sky-shards#74]
On the legacy timeline, the order is wrong. I think it just needs to be moved back one 
![image](https://github.com/PlutoyDev/sky-shards/assets/149901272/54c8177d-ff4e-4bfd-a5e3-e93069622227)

This is what I mean when it needs to be moved back one. Also not sure why that 12:00:00 AM is there at the start of the timeline
![image](https://github.com/PlutoyDev/sky-shards/assets/149901272/fcde1a95-2de4-4cb8-9d46-e56c5d0e30d9)

On the non-legacy timeline it's all fine
![image](https://github.com/PlutoyDev/sky-shards/assets/149901272/5c983ec7-cf7e-4a1f-8cd7-1357c38e8221)

**Comment by PlutoyDev** [comment]
Sorry, my bad the progress bar was set to display sky (America/Los_Angeles) timezone instead of the timezone in the user setting. 
The fix has been deployed as of c01606d997b2817e1edaf2cbecb4ccb262f26dcd
